Bump to 0.4.2
`FlutterForegroundPlugin` is now public. Might fix this:
```
error: FlutterForegroundPlugin() has private access in FlutterForegroundPlugin
    flutterEngine.getPlugins().add(new changjoopark.com.flutter_foreground_plugin.FlutterForegroundPlugin());
```